#!/bin/sh

for mac in $(ls /lib/gluon/treatment/macs); do
	# check if filename is a valid MAC address
	if expr "$mac" : "[a-fA-F0-9]\{2\}\(:[a-fA-F0-9]\{2\}\)\{5\}" >/dev/null; then
		# check if the current MAC matches this nodes MAC
		ip link show br-client | grep -qi "$mac"
		if [ "$?" == "0" ]; then
			/bin/sh "/lib/gluon/treatment/macs/$mac"
		fi
	fi
done

# try opkg remove 
opkg remove gluon-treatment
# delete cronjob manually (in case opkg didn't work)
rm /usr/lib/micron.d/treatment
# delete script and mac treatments
rm -rf /lib/gluon/treatment

    Contact GitHub API Training Shop Blog About 

    © 2017 GitHub, Inc. Terms Privacy Security Status Help 

