#!/usr/bin/lua


local uci = require('luci.model.uci').cursor()

local config = 'rsk'



-- rsk.@nightswitch[0]=nightswitch
if not uci:get_first(config, 'nightswitch') then
  -- print ("no valid config found")
  -- Let's check filesystem
  local file_found=io.open("/etc/config/rsk", "r")
  if file_found==nil then
        -- we write a new one ...
        -- print ("no rsk config-file ... creating...")
        local file = io.open("/etc/config/rsk", "w")
        file:write("config nightswitch\n")
        file:write("      option houroff '22'\n")
        file:write("      option houron '6'\n")
        file:write("      option disabled '1'\n")
        file:write("\n")
        file:write("config checkmesh\n")
        file:write("      option disabled '1'\n")
        file:write("      option minclients '1'\n")
        file:write("      option maxfail '5'\n")
        file:write("\n")
        file:write("config checkgw\n")
        file:write("      option disabled '1'\n")
        file:write("      option mac3gw 'b0:49:5e'\n")
        file:write("      option maxfail '5'\n")
        file:write("\n")
        file:write("config ssidchanger\n")
        file:write("      option disabled '0'\n")
        file:write("      option limitlow '45'\n")
        file:write("      option limithigh '55'\n")
        file:close()
   end
   else
    -- print ("config file already exists")

end
