#!/bin/sh
echo "switch to soznet"
# autoupater
uci set autoupdater.settings=autoupdater
uci set autoupdater.settings.branch='stable'
uci set autoupdater.settings.version_file='/lib/gluon/release'
uci set autoupdater.settings.enabled='1'
uci set autoupdater.experimental=branch
uci set autoupdater.experimental.mirror='http://[2a03:2260:3017:100::2]/sozialenetzwerke/experimental/sysupgrade' 'http://firmware.ffsu/sozialenetzwerke/experimental/sysupgrade' 'http://firmware.freifunk-siegburg.de/sozialenetzwerke/experimental/sysupgrade'
uci set autoupdater.experimental.good_signatures='2'
uci set autoupdater.experimental.name='experimental'
uci set autoupdater.experimental.pubkey='88bfb774de03b069966c24b322cd6c08ff8748398d42f633bb55eae832ca4eaa' 'b1848a78b33b532e60a44e43429432ffea4b2962f2fb4008e22c28045592430' '101ca1881f2dbb6a9446dc8288f1264dddca2bf4fc2026a267e71ae2b44656ea' 'fae080f9b05f3457bbd8fb21be9e1b32c7dadcefb0af11ad729970aee44f8a9d' '500ac04af59da09e4e62c8df63bc8b9d3c0fe251d336fddfc0b176d0eecb72a7' '2647b9fec75e130e153728ee8fad14b24764f23637eb9f3b0a68f2a279a74914'
uci set autoupdater.beta=branch
uci set autoupdater.beta.mirror='http://[2a03:2260:3017:100::2]/sozialenetzwerke/beta/sysupgrade' 'http://firmware.ffsu/sozialenetzwerke/beta/sysupgrade' 'http://firmware.freifunk-siegburg.de/sozialenetzwerke/beta/sysupgrade'
uci set autoupdater.beta.good_signatures='2'
uci set autoupdater.beta.name='beta'
uci set autoupdater.beta.pubkey='88bfb774de03b069966c24b322cd6c08ff8748398d42f633bb55eae832ca4eaa' 'b1848a78b33b532e60a44e43429432ffea4b2962f2fb4008e22c28045592430' '101ca1881f2dbb6a9446dc8288f1264dddca2bf4fc2026a267e71ae2b44656ea' 'fae080f9b05f3457bbd8fb21be9e1b32c7dadcefb0af11ad729970aee44f8a9d' '500ac04af59da09e4e62c8df63bc8b9d3c0fe251d336fddfc0b176d0eecb72a7' '2647b9fec75e130e153728ee8fad14b24764f23637eb9f3b0a68f2a279a74914'
uci set autoupdater.stable=branch
uci set autoupdater.stable.mirror='http://[2a03:2260:3017:100::2]/sozialenetzwerke/stable/sysupgrade' 'http://firmware.ffsu/sozialenetzwerke/stable/sysupgrade' 'http://firmware.freifunk-siegburg.de/sozialenetzwerke/stable/sysupgrade'
uci set autoupdater.stable.good_signatures='2'
uci set autoupdater.stable.name='stable'
uci set autoupdater.stable.pubkey='88bfb774de03b069966c24b322cd6c08ff8748398d42f633bb55eae832ca4eaa' 'b1848a78b33b532e60a44e43429432ffea4b2962f2fb4008e22c28045592430' '101ca1881f2dbb6a9446dc8288f1264dddca2bf4fc2026a267e71ae2b44656ea' 'fae080f9b05f3457bbd8fb21be9e1b32c7dadcefb0af11ad729970aee44f8a9d' '500ac04af59da09e4e62c8df63bc8b9d3c0fe251d336fddfc0b176d0eecb72a7' '2647b9fec75e130e153728ee8fad14b24764f23637eb9f3b0a68f2a279a74914'
uci commit autoupdater
#
# site code

# mesh id
uci set wireless.mesh_radio0.mesh_id='su-snw-mesh'
uci commit wireless
#
# tunneldigger
uci set tunneldigger.@broker[0].address='fgw01.freifunk-siegburg.de:20005' 'fgw02.freifunk-siegburg.de:20005' 'fgw03.freifunk-siegburg.de:20005'
uci commit tunneldigger
# ssid change
# uci set wireless.client_radio0.ssid='Freifunk'
uci set wireless.client_radio0.ssid='manus manum lavat'
uci commit wireless
